Removed .encode() that was causing this regression with python2.
File "/root/DIGITS/digits/device_query.py", line 259, in get_nvml_info
    raise RuntimeError('nvmlDeviceGetHandleByPciBusId() failed with error #%s' % rc)
RuntimeError: nvmlDeviceGetHandleByPciBusId() failed with error #2

Removed python2/3 from digits-devserver so that each virtual env can launch the appropriate version